Hw 08 spring
ivlytvynets/cinema-service pull request #11
Opened 2021-02-18 21:48 UTC by ivlytvynets

2021-02-21 15:21 UTC, gigbat approved these changes

2021-02-22 09:20 UTC, Sofasmile requested changes

2021-02-22 09:20 UTC, Sofasmile commented on src/main/java/com/dev/cinema/controller/DataInitializer.java
> +        Role role = new Role();
let's add USER role too

2021-02-22 09:20 UTC, Sofasmile commented on src/main/java/com/dev/cinema/model/User.java
> +    private Role role;
user can have a lot of roles, so let's use set of roles here

2021-02-22 09:20 UTC, Sofasmile commented on src/main/java/com/dev/cinema/security/CustomUserDetailsService.java
> +    private final PasswordEncoder passwordEncoder;
PasswordEncoder is redundant here

2021-02-22 15:09 UTC, Sofasmile requested changes
we should add `join` for method getUserByEmail to get roles with user

2021-02-22 15:09 UTC, Sofasmile commented on src/main/java/com/dev/cinema/security/CustomUserDetailsService.java
> +        userBuilder.roles(user.getRoles().toString());
does user.getRoles().toString() work correctly?

2021-02-22 15:30 UTC, Sofasmile requested changes
be attentive
![image](https://user-images.githubusercontent.com/36365171/108729892-abbcef80-7533-11eb-8e72-9ccd9aeb3f7c.png)

2021-02-22 15:30 UTC, Sofasmile commented on src/main/java/com/dev/cinema/security/CustomUserDetailsService.java
> +                .collect(Collectors.joining()));
правильно повертати тут масив стрінгів з roleName

2021-02-23 09:41 UTC, Sofasmile approved these changes

2021-02-23 09:41 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/impl/UserDaoImpl.java
> +            Query<User> query = session.createQuery("from User u left join fetch u.roles r "
чому саме left join? В нас може бути ситуація коли юзер буде без ролі? Як на мене то це не валідна поведінка програми

2021-02-23 09:48 UTC, merged